defaults:
  - default.yaml

fairness_metric_name: "spd"
sensitive_attributes: ${data.dataset.sensitive_attributes}
eps: 0.05
maxiter: 10
popsize: 10
tol: 0.01
mutation: [0.5, 1]
recombination: 0.7
workers: 1
seed: ${exp.seed}
