run:
  dir: ${paths.root_dir}/outputs/bias_mitigation/${data.dataset.dataset_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ${paths.root_dir}/outputs/bias_mitigation/${data.dataset.dataset_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: FL_algorithm=${keep_last_str:${method.name}},data_cleaning=${data.cleaning.name}/exp_seed=${exp.seed},data_seed=${data.seed}
