run:
  dir: ${paths.root_dir}/outputs/${data.dataset.dataset_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ${paths.root_dir}/outputs/${data.dataset.dataset_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}_${sanitize_override_dirname:${hydra.job.override_dirname}}

job:
  config:
    override_dirname:
      exclude_keys:
        - experiment
