run:
  dir: ${paths.root_dir}/outputs/overall_impact/${data.dataset.dataset_name}/alpha=${data.distribution.alpha}

sweep:
  dir: ${paths.root_dir}/outputs/overall_impact/${data.dataset.dataset_name}/alpha=${data.distribution.alpha}
  subdir: model=${keep_last_str:${method.hyperparameters.model}}/data_cleaning=${data.cleaning.name}/exp_seed=${exp.seed},data_seed=${data.seed}
