# @package _global_

defaults:
  - _self_
  - data: default.yaml
  - eval: all.yaml
  - exp: default.yaml
  - hydra: default.yaml
  - logger: default.yaml
  - method: default.yaml
  - paths: default.yaml
  - protocol: default.yaml
  - save: default.yaml
